on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n containerregistry789 -g containerregistry789b4a1-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n containerregistry789 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n containerregistry789 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n containerregistry789 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: containerregistry789.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/https://github.com/kstaken/dockerfile-examples" -f  "https://github.com/kstaken/dockerfile-examples" -t containerregistry789.azurecr.io/kubecluster1:${{ github.sha }}
        docker push containerregistry789.azurecr.io/kubecluster1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kubecluster1_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubecluster1bb11-sanjay1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubecluster1bb11-sanjay1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubecluster1bb11-sanjay1
        container-registry-url: containerregistry789.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kubecluster1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubecluster1bb11-sanjay1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerregistry789.azurecr.io/kubecluster1:${{ github.sha }}
        imagepullsecrets: |
          kubecluster1dockerauth